name: sihutama
description: SiHutama — Aplikasi SMK Hutama (CBT & Bimbingan Konseling)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^13.2.0
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.3.9
  pdf: ^3.13.0
  printing: ^5.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo.png"
  android_12:
    color: "#FFFFFF"
    image: "assets/images/logo.png"
  ios: true
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
